AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for the Lichess bot.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: lichess-bot
