AWSTemplateFormatVersion: "2010-09-09"
Description: Infrastructure for the Lichess bot.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    Properties:
      BucketName: lichess-bot
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          # allow SES to write emails to bucket /emails/
          # https://docs.aws.amazon.com/ses/latest/DeveloperGuide/receiving-email-permissions.html#receiving-email-permissions-s3
          - Effect: Allow
            Principal:
              Service: "ses.amazonaws.com"
            Action: s3:PutObject
            Resource: !Sub "${S3Bucket.Arn}/emails/*"
            Condition:
              StringEquals:
                aws:Referer: !Ref AWS::AccountId

  Repository:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: lichess-bot

  ExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lichess-bot-execution-role
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
            Action:
              - "sts:AssumeRole"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy

  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      ContainerDefinitions:
        - Name: lichess-bot
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/lichess-bot:latest"
          ReadonlyRootFilesystem: true
          # LogConfiguration: #https://docs.aws.amazon.com/AmazonECS/latest/developerguide/using_awslogs.html
          # Secrets: #https://docs.aws.amazon.com/AmazonECS/latest/developerguide/specifying-sensitive-data.html
      Cpu: 1024 # 1 vCPU
      Family: lichess-bot
      Memory: 2048 # 2Gb
      NetworkMode: awsvpc # required for fargate
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !Ref ExecutionRole
      # TaskRoleArn: # will need a task role for S3 Syzygy download, metadata poll for spot termination
      # Volumes: # https://docs.aws.amazon.com/AmazonECS/latest/developerguide/fargate-task-storage.html

Outputs:
  Repository:
    Value: !GetAtt Repository.Arn
