on: [push]
name: Test
jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        go-version: [1.13.x, 1.14.x]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dependencies
        run: |
          go get ./...
          go get github.com/matryer/moq
          go get golang.org/x/tools/cmd/stringer
      - name: Generate
        run: go generate ./...
      - name: Test
        run: go test -short ./...
